### ISSUE TITLE
Missing .env

### ISSUE THREAD

**Issue by thelitsune** [Kumala3/shop-pomidor4ik#1]
It says to change a file to .env but that file is nowhere to be found. I think I manaed to find one in one of your other projects but not on this one.

**Comment by thelitsune** [comment]
docker-compose up --build
time="2024-05-21T13:00:25-04:00" level=warning msg="The \"REDIS_PORT\" variable is not set. Defaulting to a blank string."
time="2024-05-21T13:00:25-04:00" level=warning msg="The \"REDIS_PASSWORD\" variable is not set. Defaulting to a blank string."
time="2024-05-21T13:00:25-04:00" level=warning msg="F:\\Telegram Bots\\shop-admin\\docker-compose.yml: `version` is obsolete"
env file F:\Telegram Bots\shop-admin\.env not found: CreateFile F:\Telegram Bots\shop-admin\.env: The system cannot find the file specified.

**Comment by Kumala3** [comment]
> It says to change a file to .env but that file is nowhere to be found. I think I manaed to find one in one of your other projects but not on this one.

## Thank you for informing me about the lack of `.env.dist` file as an example of the actual `.env` file.

### I have already fixed this issue, therefore, pull new changes and do the steps to run the project.

### If you have any other questions related to this project, feel free to ask me anytime, via my contacts or open a new issue.
